#!/bin/sh
#DEBHELPER#
set -e
libpath="/usr/lib/serials"
qtlibpath="/usr/lib/x86_64-linux-gnu"
pluginspath="/usr/lib/x86_64-linux-gnu/qt5/plugins"
bin="/usr/bin"
sbin="/usr/sbin"

  if [ -d "/root/桌面" ]; then
      cp /usr/share/applications/serialport-assistant.desktop /root/桌面
      chmod +x  /root/桌面/serialport-assistant.desktop
  fi

  if [ -d "/root/Desktop" ]; then
      cp /usr/share/applications/serialport-assistant.desktop /root/Desktop
      chmod +x  /root/Desktop/serialport-assistant.desktop
  fi

   for FILENAME in /home/*; do

   if [ -d "${FILENAME}/桌面" ]; then
	     usrname=${FILENAME##*/}
	     su - ${usrname} -c " cp /usr/share/applications/serialport-assistant.desktop /home/$usrname/桌面"
	     chmod +x  /home/$usrname/桌面/serialport-assistant.desktop
   fi

   if [ -d "${FILENAME}/Desktop" ]; then
	     usrname=${FILENAME##*/}
	       su - ${usrname} -c  "cp /usr/share/applications/serialport-assistant.desktop /home/$usrname/Desktop"
	      chmod +x  /home/$usrname/Desktop/serialport-assistant.desktop
   fi

   done

chmod +x ${libpath}/serials.sh
chmod +x ${libpath}/serialsdbus.sh
chmod +x ${bin}/serials
chmod +x ${sbin}/serialsdbus

unset libpath
unset qtlibpath
unset pluginspath
unset bin
	      
 












