#!/bin/sh
set -e
#DEBHELPER#
libpath="/usr/lib/serials"
qtlibpath="/usr/lib/x86_64-linux-gnu"
 bin="/usr/bin"

 if [ -d "$HOME/桌面" ]; then
      rm -f  $HOME/桌面/serialport-assistant.desktop
 fi

 if [-d "$HOME/Desktop"];then
     rm -f $HOME/Desktop/serialport-assistant.desktop
 fi

unset libpath
unset qtlibpath
unset bin
