/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp common.xml -c commonAdaptor -a commonAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COMMONADAPTOR_H_1441524011
#define COMMONADAPTOR_H_1441524011

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.common
 */
class commonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.common")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.common\">\n"
"    <method name=\"Dbus_wSettings\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_setValue\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_setValue\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_setValue\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_setValue\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"w\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"h\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_value\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"out\" type=\"v\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_wSettings_RectValue\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"key\"/>\n"
"      <arg direction=\"out\" type=\"a{i}\" name=\"value\"/>\n"
"      <annotation value=\"QRect\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    commonAdaptor(QObject *parent);
    virtual ~commonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Dbus_wSettings(const QString &path);
    QRect Dbus_wSettings_RectValue(const QString &key);
    void Dbus_wSettings_setValue(const QString &key, int x, int y, int w, int h);
    void Dbus_wSettings_setValue(const QString &key, int value);
    void Dbus_wSettings_setValue(const QString &key, bool value);
    void Dbus_wSettings_setValue(const QString &key, const QString &value);
    QDBusVariant Dbus_wSettings_value(const QString &key);
Q_SIGNALS: // SIGNALS
};

#endif
