/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c serialsAdaptor -a serialsAdaptor.h:serialsAdaptor.cpp serials.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SERIALSADAPTOR_H_1428222553
#define SERIALSADAPTOR_H_1428222553
#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.serials
 */
class serialsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.serials")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.serials\">\n"
"    <method name=\"Dbus_serial_open\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_clear\"/>\n"
"    <method name=\"Dbus_serial_setPortName\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"portname\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_setBaudRate\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"baudrate\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_setDataBits\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"databit\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_setParity\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"parity\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_setStopBits\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"stopbits\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_setFlowControl\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"flowcontrol\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_close\"/>\n"
"    <method name=\"Dbus_serial_write\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"a\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"n\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_write\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"data\"/>\n"
"    </method>\n"
"    <method name=\"Dbus_serial_readAll\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"response\"/>\n"
"    </method>\n"
"    <signal name=\"Dbus_serial\"/>\n"
"  </interface>\n"
        "")
public:
    serialsAdaptor(QObject *parent);
    virtual ~serialsAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Dbus_serial_clear();
    void Dbus_serial_close();
    bool Dbus_serial_open();
    QByteArray Dbus_serial_readAll();
    void Dbus_serial_setBaudRate(int baudrate);
    void Dbus_serial_setDataBits(int databit);
    void Dbus_serial_setFlowControl(int flowcontrol);
    void Dbus_serial_setParity(int parity);
    void Dbus_serial_setPortName(const QString &portname);
    void Dbus_serial_setStopBits(int stopbits);
    void Dbus_serial_write(const QString &data);
    void Dbus_serial_write(int data);
Q_SIGNALS: // SIGNALS
    void Dbus_serial();
private slots:
    void Dbus_readSerial();
};

#endif
